import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#2e4b57",
        "inverse-primary": "#ffb3ac",
        "on-background": "#1a1c1c",
        "on-surface-variant": "#5b403d",
        outline: "#8f6f6c",
        error: "#ba1a1a",
        "on-primary-fixed-variant": "#930010",
        surface: "#f9f9f9",
        "inverse-surface": "#2f3131",
        "surface-tint": "#ba1a20",
        "surface-container-high": "#e8e8e8",
        tertiary: "#3f5b69",
        "on-primary-container": "#fff2f0",
        "primary-fixed": "#ffdad6",
        "on-secondary": "#ffffff",
        "tertiary-container": "#577482",
        "primary-container": "#d32f2f",
        "on-secondary-fixed-variant": "#474646",
        primary: "#af101a",
        "inverse-on-surface": "#f1f1f1",
        "on-tertiary-container": "#e9f7ff",
        "surface-container": "#eeeeee",
        secondary: "#5f5e5e",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#656464",
        "surface-variant": "#e2e2e2",
        "outline-variant": "#e4beba",
        "surface-bright": "#f9f9f9",
        "on-error-container": "#93000a",
        "surface-dim": "#dadada",
        "on-error": "#ffffff",
        "secondary-fixed": "#e5e2e1",
        "surface-container-highest": "#e2e2e2",
        "primary-fixed-dim": "#ffb3ac",
        "secondary-container": "#e5e2e1",
        background: "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#001f2a",
        "on-secondary-fixed": "#1c1b1b",
        "secondary-fixed-dim": "#c8c6c5",
        "on-primary-fixed": "#410003",
        "tertiary-fixed": "#c9e7f7",
        "surface-container-low": "#f3f3f3",
        "error-container": "#ffdad6",
        "on-surface": "#1a1c1c",
        "tertiary-fixed-dim": "#adcbda",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "section-padding": "80px",
        "margin-mobile": "16px",
        base: "8px",
        gutter: "24px",
        "container-max": "1280px",
      },
      fontFamily: {
        "label-bold": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
      },
      fontSize: {
        "label-bold": ["14px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": [
          "32px",
          {
            lineHeight: "1.2",
            letterSpacing: "-0.01em",
            fontWeight: "700",
          },
        ],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "1.2", fontWeight: "700" },
        ],
        "display-lg": [
          "48px",
          {
            lineHeight: "1.1",
            letterSpacing: "-0.02em",
            fontWeight: "800",
          },
        ],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};

export default config;
